platform :ios, '6.1'
pod 'AFNetworking', '~> 2.4.1'
pod 'FMDB', '~> 2.4'
pod 'EGOImageLoading', '~> 0.0.1'
pod 'FXBlurView', '~> 1.6.3'
pod 'MMProgressHUD', '~> 0.3.1'
pod 'AdsMoGo-iOS-Lib',:git=>'https://github.com/chensj1901/AdsMoGo-iOS-Lib.git'
pod 'STColorPicker', '~> 1.0.0'